name: Release Extension

on:
  release:
    types: [created]

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Extension Dependencies
        run: |
          npm install
          npm install -g vsce

      - name: Build Extension
        run: vsce package

      - name: Publish to Marketplace
        run: vsce publish -p $PUBLISHER_TOKEN
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}